Merge repositories
dative/mmisi-frontend pull request #12
Opened 2022-05-10 18:32 UTC by jozemaria

## Completion of week 1 task

### Tasks [week 1]

- [x] Create a fork of this repo
- [x] Clone your fork to your local dev environment
- [x] Install the dependencies and run the `npm run dev` command without issues
- [x] Confirm access to the design Figma file
- [x] Review the implementation approach with Lead Developer
- [x] Create website "shell" layout on `_generic_page_layout.twig`
  - [x] Review and define webfonts
  - [x] Review and define colors
  - [x] Review and define containers
  - [x] Implement `_site_header.twig` component
  - [x] Implement `_site_footer.twig` component
  - [x] Implement `typography.twig` page
  - [x] Make sure non-photo images are either inline SVG or URL encoded when used in CSS.

2022-05-11 00:45 UTC, webrgp requested changes
Thanks for your submission! Lots of good work!

I've add the comments to the files.

2022-05-11 00:45 UTC, webrgp commented on src/css/app.css
> +@import url('./components/hamburgers.css');
No need for the `url(...)`. Should just be:

`@import './components/hamburger.css';`

Also, why place at the end and not with the other "components"?

2022-05-11 00:45 UTC, webrgp commented on src/css/components/hamburgers.css
> +/*!
Great job grabbing the css! But you missed the next step: removing all the other animation styles that are not the **Squeeze**. All other animations that comes with that library are "dead weight" and should be removed.

2022-05-11 00:45 UTC, webrgp commented on src/templates/_layouts/_generic_page_layout.twig
> +  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
These link tags are already set on lines 28-29

2022-05-11 00:45 UTC, webrgp commented on src/templates/_layouts/_generic_page_layout.twig
> +  <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&display=swap" rel="stylesheet">
Fira Mono isn't part of the typography.

2022-05-11 00:45 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +        class="flex flex-row px-12 divide-x-2 divide-plum-light py-2 text-sm justify-center md:justify-end">
Good job using the `divide` class!

2022-05-11 00:45 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +        </div>
Those should be anchor tags `<a>...</a>`

2022-05-11 00:45 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +                      Save Changes
Should be **Schedule a Call**

2022-05-11 00:45 UTC, webrgp commented on src/templates/index.twig
> +</div>
View https://github.com/dative/mmisi-frontend/issues/8#issuecomment-1123053011

2022-05-11 00:45 UTC, webrgp commented on src/templates/typography.twig
> +<section class="p-3">
View https://github.com/dative/mmisi-frontend/issues/8#issuecomment-1123053011

2022-05-11 00:45 UTC, webrgp commented on tailwind.config.js
> +      mono: ['Fira Mono', 'sans-serif'],
Fira Mono not part of the designs.

2022-05-11 01:24 UTC, jozemaria commented on src/templates/_layouts/_generic_page_layout.twig
> +  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
Removed! Thanks.

2022-05-11 01:25 UTC, jozemaria commented on src/templates/_layouts/_generic_page_layout.twig
> +  <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&display=swap" rel="stylesheet">
I used it because of the use of the 'pre' tag, to put a more similar font. Because the tag was breaking the page.

Removed.

2022-05-11 01:26 UTC, jozemaria commented on src/templates/_partials/_site_header.twig
> +        class="flex flex-row px-12 divide-x-2 divide-plum-light py-2 text-sm justify-center md:justify-end">
Thanks!

2022-05-11 01:28 UTC, jozemaria commented on src/templates/_partials/_site_header.twig
> +        </div>
Resolved.

2022-05-11 01:30 UTC, jozemaria commented on tailwind.config.js
> +      mono: ['Fira Mono', 'sans-serif'],
Removed.

2022-05-11 01:38 UTC, jozemaria commented on src/css/app.css
> +@import url('./components/hamburgers.css');
I used VSCode suggestion and ended up importing with ```url(...)```, adjusted.

I chose to save to this location for the organization, do you think it would be better to save to the _partials folder?

2022-05-11 01:41 UTC, webrgp commented on src/css/app.css
> +@import url('./components/hamburgers.css');
The location of the file is correct. I meant the location inside the `app.css`. Instead of line 59, you could have place it on line 35, right after `@import './components/global.css';`

2022-05-11 01:47 UTC, webrgp requested changes

2022-05-11 01:47 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +          <nav class="flex-1 md:max-w-[485px] hidden md:block md:flex md:items-center">
Just caught this one: you have both `md:block` and `md:flex` in the class. They both happen at the `md` breakpoint and override the same `display` css property. VSCode should have picked up that, and if it didn't you need to install the extensions in the `.vscode/extensions.json` file. 

This is what I see on my VSCode:

![Screen Shot 2022-05-10 at 9 44 57 PM](https://user-images.githubusercontent.com/994788/167752234-0a22c10b-2eaa-45e0-af22-3043bbf6ea8c.png)

2022-05-11 01:47 UTC, jozemaria commented on src/css/app.css
> +@import url('./components/hamburgers.css');
Oh, I got it. I didn't pay attention to that detail. I will adjust. Thanks

2022-05-11 01:54 UTC, jozemaria commented on src/templates/_partials/_site_header.twig
> +          <nav class="flex-1 md:max-w-[485px] hidden md:block md:flex md:items-center">
My VScode was the same, I thought I had it removed before committing...

My fault, I solved it by removing the ```md:flex``` from the class.

It's working normally.

2022-05-11 02:08 UTC, jozemaria commented on src/templates/index.twig
> +</div>
Thanks

2022-05-11 02:08 UTC, jozemaria commented on src/templates/typography.twig
> +<section class="p-3">
Thanks

2022-05-11 23:56 UTC, webrgp requested changes

2022-05-11 23:56 UTC, webrgp commented on src/templates/typography.twig
> +      <h1 class="leading-tight font-medium text-4xl mb-7 md:text-5xl">Didn't melt
Styling should be applied without add class to the elements. Maybe put a wrapper element with a class and perform the styling on the css file?

2022-05-12 23:24 UTC, webrgp requested changes
Excellent job!

2022-05-12 23:24 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +    </div>
Great job! The only problem is that I can't scroll to the first item on the left (COVID).

![localhost_3030_(iPhone SE)](https://user-images.githubusercontent.com/994788/168182807-b16ece3b-ea15-4464-a8be-66ef2fdd9f67.png)

2022-05-12 23:24 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +    </div>
Too much vertical space on desktop.

<img width="371" alt="Screen Shot 2022-05-12 at 7 16 28 PM" src="https://user-images.githubusercontent.com/994788/168182900-83449faa-b312-442d-8fc9-779ea881e65d.png">

2022-05-13 12:29 UTC, webrgp requested changes

2022-05-13 12:29 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +                  <button class="rounded-lg bg-plum p-5 hover:bg-plum-dark
The button doesn't have a solid background color.

2022-05-13 12:40 UTC, webrgp requested changes
Almost there!

2022-05-13 12:45 UTC, webrgp requested changes

2022-05-13 12:45 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +    <div class="flex flex-row px-3 justify-between items-center md:z-10 md:mt-[-15px]">
`items-center` should be `items-end`

2022-05-13 12:45 UTC, jozemaria commented on src/templates/_partials/_site_header.twig
> +                  <button class="rounded-lg bg-plum p-5 hover:bg-plum-dark
I thought it was changed lol

2022-05-13 13:17 UTC, closed without merging