Week 1
dative/mmisi-frontend pull request #14
Opened 2022-05-11 19:21 UTC by Gabsop

There is my week 1 tasks!

2022-05-11 19:22 UTC, Gabsop commented
I just have a question, in the typography.css I had to put the "!important" on every single line for it to be able to work. Why?

2022-05-11 19:43 UTC, Melnatal commented
I believe there is no need, nor is it advisable to use "!important".
You have to use the @layer components in the typography.twig file and name the component "typography" or whatever.
In the index.twig file you forgot to name the class="" before the <section>
And also I had understood that we can't use index.twig to add typography.

""I've seen a common mistake today from pretty much everyone I've spoken to: include the typography.twig inside de index.twig page.

The typography.twig file should be a page, just like the index.twig page, not part of it. It should be created at the same level as the index.twig, with pretty much the same code, but replacing the content with the typography content."'(words by Rodrigo)

I hope I made myself understood.

2022-05-11 20:36 UTC, Gabsop commented
Thanks @Melnatal, I fixed! The problem was that I writed
```
@layer typography {
    .typography {
        ...
    }
}
```
But the correct way was to use:
```
@layer components {
    .typography {
        ...
    }
}
```

2022-05-12 23:39 UTC, webrgp requested changes

2022-05-12 23:39 UTC, webrgp commented on src/templates/_partials/_logo_color.svg.twig
> +<svg width="255" height="101" fill="none" xmlns="http://www.w3.org/2000/svg"><title>Murray and McDonald Insurance Services, Inc.</title><path d="m59.4922 80.0702-5.3695-13.9668-.0406 10.2396v.7372c0
The `_logo_color.svg.twig` has two sizes, one for mobile and one for desktop.

2022-05-12 23:39 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +	</section>
Too much vertical space.

<img width="371" alt="Screen Shot 2022-05-12 at 7 16 28 PM" src="https://user-images.githubusercontent.com/994788/168183880-52590a13-077d-482e-918b-e295e492cfb6.png">

Also, there is no max width until it hits 1440px:

<img width="697" alt="Screen Shot 2022-05-12 at 7 28 54 PM" src="https://user-images.githubusercontent.com/994788/168184012-2dc88f87-8044-4c08-bb43-1a8a93ab5fc3.png">

2022-05-12 23:39 UTC, webrgp commented on src/templates/typography.twig
> +{% endblock %}
Wrong page background color.

2022-05-12 23:39 UTC, webrgp commented on tailwind.config.js
> +      'background': '#E5E5E5',
🧐?

2022-05-13 00:43 UTC, Gabsop commented on src/templates/_partials/_logo_color.svg.twig
> +<svg width="255" height="101" fill="none" xmlns="http://www.w3.org/2000/svg"><title>Murray and McDonald Insurance Services, Inc.</title><path d="m59.4922 80.0702-5.3695-13.9668-.0406 10.2396v.7372c0
Fixed!

2022-05-13 00:43 UTC, Gabsop commented on src/templates/_partials/_site_header.twig
> +	</section>
Fixed!

2022-05-13 00:43 UTC, Gabsop commented on src/templates/typography.twig
> +{% endblock %}
Fixed!

2022-05-13 00:44 UTC, Gabsop commented on tailwind.config.js
> +      'background': '#E5E5E5',
I really don't remember adding this 😅 but i fixed! Thanks!

2022-05-13 01:01 UTC, webrgp requested changes

2022-05-13 01:01 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +	<section class="flex flex-row items-center justify-between px-3">
Needs to set `max-w-screen-lg` here too.

<img width="1918" alt="Screen Shot 2022-05-12 at 9 00 34 PM" src="https://user-images.githubusercontent.com/994788/168190824-f2a4ea39-d943-4c1e-b791-5a1d0353e8e1.png">

2022-05-13 01:26 UTC, Gabsop commented on src/templates/_partials/_site_header.twig
> +	<section class="flex flex-row items-center justify-between px-3">
Fixed! I added the `max-screen-lg` and `mx-auto` to the `<header>` itself so that both sections took the rule.

2022-05-13 13:23 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +	</section>
Still too much vertical space on desktop.

2022-05-13 13:25 UTC, webrgp requested changes

2022-05-13 13:25 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +		<ul class="flex flex-row items-center justify-center md:justify-end md:bg-white bg-plum-lightest">
Still too much vertical space on desktop.

2022-05-13 15:10 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +		<ul class="flex flex-row items-center justify-center md:justify-end md:bg-white bg-plum-lightest">
Have you tried negative bottom margin on the container element above the logo's container element?

2022-05-13 15:16 UTC, Gabsop commented on src/templates/_partials/_site_header.twig
> +		<ul class="flex flex-row items-center justify-center md:justify-end md:bg-white bg-plum-lightest">
Actually I used bottom-3 to make it higher, and thats the result. Is it enough?
![image](https://user-images.githubusercontent.com/50323251/168314570-f944b96f-4b59-4b23-b282-f9b2e45347fc.png)

2022-05-13 15:41 UTC, Gabsop commented on src/templates/_partials/_site_header.twig
> +		<ul class="flex flex-row items-center justify-center md:justify-end md:bg-white bg-plum-lightest">
I tweaked the size of the logo and the bottom to 5 and I think I got it just like the figma file.
![image](https://user-images.githubusercontent.com/50323251/168318899-0e31b9ad-744a-40ef-9e4a-8e23b427eb3b.png)

Figma file:
![image](https://user-images.githubusercontent.com/50323251/168319002-437c3fe1-125b-4d48-81ba-756ce57e1092.png)
![image](https://user-images.githubusercontent.com/50323251/168319024-17f2f401-e78e-42f6-8585-606ecc023d6f.png)

2022-05-13 19:09 UTC, webrgp reviewed
Thanks! I will review and be in touch soon.

2022-05-13 19:18 UTC, closed without merging