Week 1
dative/mmisi-frontend pull request #15
Opened 2022-05-12 03:09 UTC by diegocosta-dev

> ### Tasks
> * [x]  Create a fork of this repo
> * [x]  Clone your fork to your local dev environment
> * [x]  Install the dependencies and run the `npm run dev` command without issues
> * [x]  Confirm access to the design Figma file
> * [x]  Review the implementation approach with Lead Developer
> * [x]  Create website "shell" layout on `_generic_page_layout.twig`
>   
>   * [x]  Review and define webfonts
>   * [x]  Review and define colors
>   * [x]  Review and define containers
>   * [x]  Implement `_site_header.twig` component
>   * [x]  Implement `_site_footer.twig` component
>   * [x]  Implement `typography.twig` page
>   * [x]  Make sure non-photo images are either inline SVG or URL encoded when used in CSS.

2022-05-12 15:04 UTC, diegocosta-dev commented
> Você pode criar uma classe no arquivo typography.twig: Eu criei com nome "visual", mas pode ser qualquer nomenclatura. ![image](https://user-images.githubusercontent.com/88938102/168092075-d5dcddbb-844b-423d-9cce-9a069e2b6ad5.png) e no arquivo typography.css você faz assim: Nomea com a classe e aí você não precisa adicionar para cada tag uma classe. ![image](https://user-images.githubusercontent.com/88938102/168092805-f0e96dde-48c1-4003-88d7-ba9749d51f7a.png)

Legal, vou atualizar isso no meu repositório, obrigado @Melnatal

2022-05-13 00:54 UTC, webrgp requested changes
Good job!

2022-05-13 00:54 UTC, webrgp commented on src/templates/_partials/_logo_colorful.svg.twig
> +<svg width="255" height="101" fill="none" xmlns="http://www.w3.org/2000/svg">
The _logo_colorful.svg.twig needs to display in two sizes, one for mobile and one for desktop.

2022-05-13 00:54 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +						</ul>
The styles for desktop are wrong. Check Figma.

2022-05-13 00:54 UTC, webrgp commented on src/templates/_partials/_site_header.twig
> +							<a href="{{item.url}}" class="uppercase font-medium text-plum z-10">{{item.text}}</a>
Text style is wrong. Check Figma.

2022-05-13 00:54 UTC, webrgp commented on src/templates/typography.twig
> +<div class="typography bg-plum-lightest">
background color should move to `body`.

2022-05-13 04:47 UTC, diegocosta-dev commented on src/templates/_partials/_logo_colorful.svg.twig
> +<svg width="255" height="101" fill="none" xmlns="http://www.w3.org/2000/svg">
Fixed

2022-05-13 04:48 UTC, diegocosta-dev commented on src/templates/_partials/_site_header.twig
> +						</ul>
Fixed

2022-05-13 04:48 UTC, diegocosta-dev commented on src/templates/_partials/_site_header.twig
> +							<a href="{{item.url}}" class="uppercase font-medium text-plum z-10">{{item.text}}</a>
Fixed

2022-05-13 04:48 UTC, diegocosta-dev commented on src/templates/typography.twig
> +<div class="typography bg-plum-lightest">
Fixed

2022-05-13 18:01 UTC, closed without merging